const test = [
    { text: 'Dolor pariatur Lorem sit pariatur sit. Adipisicing minim tempor do aliqua id sit minim magna velit. Fugiat qui commodo enim nulla. Sunt et anim et aliquip irure voluptate exercitation enim magna. Nisi consequat incididunt velit exercitation. Exercitation Lorem veniam mollit pariatur fugiat sint sit duis occaecat labore ex anim mollit. Do ea ut adipisicing sint sit mollit amet.' },
    { img: 'lampard.jpg' },
    { text: 'In my adventures of finding a great hosting service for my research projects at Georgia Tech, I was almost always given a preconfigured virtual machine by my advisor or the department I was building an app for. However, this is not a luxury experienced by all students and can also be a hassle to set up and configure by yourself. Little might you know, Georgia Tech web hosting (https://hosting.gatech.edu) actually provides a decent hosting service you can use for research/class projects under your advisor, assuming you’re working with a Node tech stack. You may not notice it because of it’s name: “Plesk.” It took some digging for me to discover this, which is why I’m writing this article: to save you time that you might otherwise waste. There are already many tutorials on the web for creating Express APIs with SQL databases, so I’ll let you set that up in your own time.' },
    { subtitle: 'This is so GOOD' },
    { text: 'In my adventures of finding a great hosting service for my research projects at Georgia Tech, I was almost always given a preconfigured virtual machine by my advisor or the department I was building an app for. However, this is not a luxury experienced by all students and can also be a hassle to set up and configure by yourself. Little might you know, Georgia Tech web hosting (https://hosting.gatech.edu) actually provides a decent hosting service you can use for research/class projects under your advisor, assuming you’re working with a Node tech stack. You may not notice it because of it’s name: “Plesk.” It took some digging for me to discover this, which is why I’m writing this article: to save you time that you might otherwise waste. There are already many tutorials on the web for creating Express APIs with SQL databases, so I’ll let you set that up in your own time.' },
    { subtitle: 'This is so GOOD' },
    { img: 'lampard.jpg' },
    { text: 'In my adventures of finding a great hosting service for my research projects at Georgia Tech, I was almost always given a preconfigured virtual machine by my advisor or the department I was building an app for. However, this is not a luxury experienced by all students and can also be a hassle to set up and configure by yourself. Little might you know, Georgia Tech web hosting (https://hosting.gatech.edu) actually provides a decent hosting service you can use for research/class projects under your advisor, assuming you’re working with a Node tech stack. You may not notice it because of it’s name: “Plesk.” It took some digging for me to discover this, which is why I’m writing this article: to save you time that you might otherwise waste. There are already many tutorials on the web for creating Express APIs with SQL databases, so I’ll let you set that up in your own time.' },
]


export default test;